# Generated by Django 5.0.3 on 2024-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../image.png', upload_to='category'),
        ),
    ]
